server:
  port: 7002

spring:
  application:
    name: eureka-service

eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名字
    instance-id: eureka7002
    prefer-ip-address: true
  client:
    allow-redirects: true # 是否向注册中心注册本服务：true为是
    fetch-registry: false # false表示自己是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址,多个时用逗号隔开
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/ #注册到7001


